### ISSUE TITLE
dataloader error

### ISSUE THREAD

**Issue by cy-yong** [cwmok/Conditional_LapIRN#6]
![image](https://user-images.githubusercontent.com/79499756/176084235-f2379616-14ff-4382-a48d-cd1f5dcf6691.png)
当我用我自己的数据集的时候我遇到了这样的问题，请问您能告诉我这个问题可以怎么解决吗？

**Comment by cwmok** [comment]
Hi @cy-yong,

This problem is likely related to the image size. For a 3-level LapIRN model, the input size in each dimension should be divisible by 2^4=16, e.g.: (144, 160, 192).

You may consider crop/pad-zero/resize for your image. See the example in [Train_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/master/Code/Train_LapIRN_diff_resize.py) if you want to resize your image.
